### ISSUE TITLE
Add confidence metric for single language

### ISSUE THREAD

**Issue by gogo2464** [pemistahl/lingua-rs#102]
Hello. I am doing a cryptology library. I need to detect if the text is english or not. Could you allow confidence value for a single language please?

**Comment by pemistahl** [comment]
Hi @gogo2464, I'm sorry for the late response. I'm actually planning to implement something like this, even though it's not that easy. Please stay tuned.

**Comment by gogo2464** [comment]
> 

Great ! Thank you!

**Comment by pemistahl** [comment]
No, it has not been implemented yet because this issue here is still open. As soon as the implementation is done, I will close this issue. That's how GitHub works, ok? So please refrain from asking further questions in this matter. Thank you.

**Comment by HridayM25** [comment]
Hello! 
I had a small idea to go forth with, please let me know if I am going in the correct direction or not. 
Can we calculate the absolute confidence by using
$(Total N-grams in the document profile)/$(Total out-of-place N-grams)

say for example,
English Language Profile [TH, ING, ON, ER, AND, ED]
Sample Document Profile [TH, ER, ON, LE, ING, AND]

I am using K to denote a fixed cost when N-gram is not found, we can discuss upon that.
Hence we can calculate the score as (6)/(0+2+0+K+3+1)*100

Please let me know your feedback.

**Comment by pemistahl** [comment]
@HridayM25 This issue here is for providing a method that returns a confidence value for a single language but based on the calculated values for all languages the detector has been built with.

The second step is to find a metric for which it is enough to load only the language model in question. And that's where your approach comes into play. Right, either the proportion of a language's unique ngrams or the proportion of ngrams not found in the respective language model would play a role here. So, you are basically on the right track. But it's difficult nonetheless.

**Comment by HridayM25** [comment]
Ok, thanks for the response! 
I'll try to look and learn further into this.
