### ISSUE TITLE
Long runtime of language detection

### ISSUE THREAD

**Issue by niko2342** [pemistahl/lingua-rs#11]
Hi,

I'm evaluating the lingua-rs libraray and I discovered a long running time of the following program:

```rust
#[macro_use]
extern crate lazy_static;

use std::env;
use std::fs;

use lingua::{Language, LanguageDetector, LanguageDetectorBuilder};

lazy_static! {
    static ref DETECTOR: LanguageDetector = {
        LanguageDetectorBuilder::from_languages(&[
            Language::Dutch,
            Language::English,
            Language::French,
            Language::German,
            Language::Hungarian,
            Language::Italian,
            Language::Portuguese,
            Language::Russian,
            Language::Spanish,
            Language::Finnish,
            Language::Swedish,
        ])
        .build()
    };
}

fn main() {
    let args: Vec<String> = env::args().collect();
    if args.len() != 2 {
        eprintln!("missing argument");
        std::process::exit(1);
    }

    let filename = args.get(1).unwrap();
    match fs::read_to_string(filename) {
        Ok(content) => match DETECTOR.detect_language_of(&content) {
            Some(lang) => println!("{},{}", filename, lang.iso_code_639_3()),
            _ => println!("{},", filename),
        },
        _ => println!("{},", filename),
    };

    std::process::exit(0);
}
```

First I thought the reason for the long running time could be the language detector. But even after moving this part into an `lazy_static` block, the runtime is very slow. Is a running time of 9.82 seconds to be expected with lingua for an article of 26,712 words? Are there ways to speed up the program?

I would welcome your response,
Nico

**Comment by joshrotenberg** [comment]
It's hard to say for sure without seeing your input but I suspect the long run time you're seeing is the initial `LanguageDetector` build and not the detection itself. I made a few modifications to your code below that will show you the time taken for the build and detection operations, and you can run it with multiple file arguments and see the time taken for the detection of each. Here is some sample output on my machine running against the lingua-rs `README.md`:

```
➜  linguaissue git:(master) ✗ cargo run --release ../GitHub/lingua-rs/README.md ../GitHub/lingua-rs/README.md
    Finished release [optimized] target(s) in 0.07s
     Running `target/release/linguaissue ../GitHub/lingua-rs/README.md ../GitHub/lingua-rs/README.md`
Built detecotr in: 9.917502366s
../GitHub/lingua-rs/README.md,eng
Ran detection for ../GitHub/lingua-rs/README.md in: 71.915958ms
../GitHub/lingua-rs/README.md,eng
Ran detection for ../GitHub/lingua-rs/README.md in: 74.473804ms
```

With `--release` the build takes about 9 seconds but the subsequent detections only take 71ms and 74ms. @pemistahl can probably say more about whether there are ways to speed up the build process itself.

```rust
use std::env;
use std::fs;
use std::time::Instant;

use lingua::{Language, LanguageDetector, LanguageDetectorBuilder};

fn main() {
    let args: Vec<String> = env::args().collect();
    if args.len() < 2 {
        eprintln!("missing argument");
        std::process::exit(1);
    }

    let start = Instant::now();
    let detector = build_detector();
    let duration = start.elapsed();
    println!("Built detecotr in: {:?}", duration);

    unsafe {
        for (_idx, e) in args.get_unchecked(1..).iter().enumerate() {
            let filename = e;
            let start = Instant::now();
            match fs::read_to_string(filename) {
                Ok(content) => match detector.detect_language_of(&content) {
                    Some(lang) => println!("{},{}", filename, lang.iso_code_639_3()),
                    _ => println!("{},", filename),
                },
                _ => println!("{},", filename),
            };
            let duration = start.elapsed();
            println!("Ran detection for {} in: {:?}", e, duration);
        }
    }
    std::process::exit(0);
}

fn build_detector() -> LanguageDetector {
    LanguageDetectorBuilder::from_languages(&[
        Language::Dutch,
        Language::English,
        Language::French,
        Language::German,
        Language::Hungarian,
        Language::Italian,
        Language::Portuguese,
        Language::Russian,
        Language::Spanish,
        Language::Finnish,
        Language::Swedish,
    ])
    .build()
}
```

**Comment by pemistahl** [comment]
Hi Nico, thanks for reaching out to me. 

I assume that you are using the latest release 1.1.0. In this version, the Rayon library is used internally to speed up the loading of the language models by doing it in parallel, depending on how many CPU cores you have in your machine. So this is basically as fast as it can get now. Wrapping the detector in a `lazy_static!` is useless because it does not influence the internal performance of the detector.

Loading the language models into memory is by far the most expensive step. I agree with @joshrotenberg that most of your measured 9.82 seconds are taken for this step. The actual language detection should be pretty fast by then. Josh's benchmark seems reasonable to me. Perhaps I will add some benchmarks myself for the next release. When I build the detector with the same language models as you, Nico, this takes 7 seconds on my machine (8-Core Intel Core i9), building in release mode.

Currently, all language models are loaded into memory before the first language detection is performed. In the next release 1.2.0, the models will be lazy-loaded by default to be consistent with the JVM implementation. The previous behavior can then be enabled by calling an explicit method on `LanguageDetectorBuilder`. Lazy-loading might save you some seconds if the rule engine filters out some unlikely languages from your source set. Their models will then not be loaded into memory. In any case, the startup time of *Lingua* will be longer than for other language detection libraries because its statistical models are much larger. But the actual detection should not be affected much.

**Comment by niko2342** [comment]
Thank you very much for the detailed feedback! I want to detect the language of some huge corpora (more than 8 million texts of different size) and evaluate the results against a gold standard. Therefore, the running time is very important. I changed my test program as @joshrotenberg suggested and it's significant faster than my first version. Thanks!

PS: If you are interested I can share my results.

**Comment by pemistahl** [comment]
@niko2342 How can Josh's modification make it significantly faster than before? He just added some benchmarking code. Or do you mean the difference between building the code in debug or release mode? This makes a significant difference in runtime performance indeed. If you can share your results, yes please, I'm curious.

@joshrotenberg Why have you put the code in an `unsafe` block? Does this affect performance? I think you should not create the impression that using `unsafe` is the way to go. Usually, it should be avoided and only be used under very exceptional circumstances.

**Comment by niko2342** [comment]
My initial version processed only one text at a time. The version of @joshrotenberg iterates over the filenames (given command line arguments) and builds the language detector only once.

**Comment by pemistahl** [comment]
Well, strictly speaking, this does not make your program run faster. In both cases, the detector is initialized only once. Your first program just exits after processing a single file, that's why you have to initialize the detector again for all subsequent files. Regardless, I'm glad that you could resolve your problems.

**Comment by joshrotenberg** [comment]
> @joshrotenberg Why have you put the code in an `unsafe` block? Does this affect performance? I think you should not create the impression that using `unsafe` is the way to go. Usually, it should be avoided and only be used under very exceptional circumstances.

Sorry, I only used unsafe there because I was lazy and didn't want to check `args` since I knew at that point it would at least have two elements given the earlier check. @niko2342 , `unsafe` has nothing to do with the performance so you shouldn't use it. Here is a safer version of that block: 

```rust
    if let Some(files) = args.get(1..) {
        for filename in files {
            let start = Instant::now();     
            match fs::read_to_string(filename) {
                Ok(content) => match detector.detect_language_of(&content) {
                    Some(lang) => println!("{},{}", filename, lang.iso_code_639_3()),
                    _ => println!("{},", filename), 
                },
                _ => println!("{},", filename), 
            };
            let duration = start.elapsed(); 
            println!("Ran detection for {} in: {:?}", filename, duration);
        }
    }
```

Also, if you have  plans to do more with the command line options, I suggest you take a look at [clap](https://crates.io/crates/clap).
