### ISSUE TITLE
Publish musllinux wheel

### ISSUE THREAD

**Issue by phihos** [pemistahl/lingua-rs#319]
Hi,

first of all thanks for this cool project!
I would like to build alpine Linux images with it and can not use your latest version v2.0.2 due to no musllinux wheel.
I found an example [here](https://github.com/messense/auditwheel-symbols/blob/master/.github/workflows/CI.yml#L118) how this could be accomplished.

**Comment by pemistahl** [comment]
Hi Philipp, there exists already an [issue in the lingua-py repo](https://github.com/pemistahl/lingua-py/issues/213) for Alpine Linux support. So I'm going to close this issue here. 

I don't know when I'll be able to continue the development of my library as I'm currently very busy with my daily job and family life. But I will continue, that's for sure.

**Comment by phihos** [comment]
Hi, sorry about barking up the wrong tree.
I am similarly caught up, but if I find some free time I can give it a try. I recently had to build a musllinux wheel with Maturin as well.

**Comment by pemistahl** [comment]
Musllinux wheels are now available for download on PyPI for the existing Lingua release 2.0.2. They will also be available for new releases.
