### ISSUE TITLE
Store model files in releases

### ISSUE THREAD

**Issue by thewh1teagle** [pemistahl/lingua-rs#396]
Hi,

The project looks great! Would it be possible to store the model files in the releases section instead of within the repository? Including them directly in the repo makes it quite heavy—currently, it’s around 80MB, while most of my other repositories are only a few KB. You could store the models as tar.gz files and extract them using build.rs during the build process.

Example: [sys/build.rs#L65](https://github.com/thewh1teagle/sherpa-rs/blob/main/sys/build.rs#L65)

Thanks!

**Comment by pemistahl** [comment]
Short answer: No.

Long answer: This is on purpose. I want the model files to be versioned the same way as the source code. As explained [here](https://github.com/pemistahl/lingua-rs?tab=readme-ov-file#8-how-to-add-it-to-your-project), the models are stored as optional dependencies on crates.io so that one can add Lingua as a dependency with only those languages that are relevant to the user. A [Cargo workspace](https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html) is a perfect fit for such a structure. I don't see a benefit of storing the models only in the GitHub releases page.

What is your problem with the model files being stored in the Git repository?

**Comment by thewh1teagle** [comment]
Git is not intended to store large files. It won't be efficient and when you change the model then the previous one will be kept theoretically and the size of the repo will increase more and more.
Not big deal currently if it requires too much work.
